### ISSUE TITLE
Application crashes on start

### ISSUE THREAD

**Issue by g4s8** [ammaratef45/zold-flutter-client#12]
Can't start - getting crash on start:
```
02-24 22:02:39.230 14019 14019 E flutter : [ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(733)] Could not locate FlutterCallbackInformation class
02-24 22:02:39.230 14019 14019 F flutter : [FATAL:flutter/shell/platform/android/library_loader.cc(24)] Check failed: result.
02-24 22:02:39.230 14019 14019 F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 14019 (mar.zold.wallet)
02-24 22:02:39.261 14019 14046 I ResourceExtractor: Extracted baseline resource isolate_snapshot_data
02-24 22:02:39.394  1396  1396 F DEBUG   : backtrace:
02-24 22:02:39.394  1396  1396 F DEBUG   :     #00 pc 00041f50  /system/lib/libc.so (tgkill+12)
02-24 22:02:39.394  1396  1396 F DEBUG   :     #01 pc 0003fb5d  /system/lib/libc.so (pthread_kill+32)
02-24 22:02:39.394  1396  1396 F DEBUG   :     #02 pc 0001c30f  /system/lib/libc.so (raise+10)
02-24 22:02:39.394  1396  1396 F DEBUG   :     #03 pc 000194c1  /system/lib/libc.so (__libc_android_abort+34)
02-24 22:02:39.395  1396  1396 F DEBUG   :     #04 pc 000174ac  /system/lib/libc.so (abort+4)
02-24 22:02:39.395  1396  1396 F DEBUG   :     #05 pc 001344f7  /data/app/com.ammar.zold.wallet-1/lib/arm/libflutter.so (offset 0x111000)
02-24 22:02:39.395  1396  1396 F DEBUG   :     #06 pc 00129549  /data/app/com.ammar.zold.wallet-1/lib/arm/libflutter.so (offset 0x111000) (JNI_OnLoad+488)
02-24 22:02:39.395  1396  1396 F DEBUG   :     #07 pc 0025b387  /system/lib/libart.so (_ZN3art9JavaVMExt17LoadNativeLibraryEP7_JNIEnvRKNSt3__112basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEEP8_jobjectPS9_+1238)
02-24 22:02:39.395  1396  1396 F DEBUG   :     #08 pc 002d13d7  /system/lib/libart.so (_ZN3artL18Runtime_nativeLoadEP7_JNIEnvP7_jclassP8_jstringP8_jobjectS5_+194)
02-24 22:02:39.395  1396  1396 F DEBUG   :     #09 pc 735d3105  /data/dalvik-cache/arm/system@framework@boot.oat (offset 0x1ed6000)
02-24 22:02:39.779  1396  1396 F DEBUG   :
02-24 22:02:39.779  1396  1396 F DEBUG   : Tombstone written to: /data/tombstones/tombstone_03
02-24 22:02:39.779  1396  1396 E DEBUG   : AM write failed: Broken pipe
02-24 22:02:39.781  1892 14052 W ActivityManager:   Force finishing activity com.ammar.zold.wallet/com.example.zoldwallet.MainActivity
02-24 22:02:39.792  1407  1407 I Zygote  : Process 14019 exited due to signal (6)
02-24 22:02:39.781  1892 14052 W ActivityManager:   Force finishing activity com.ammar.zold.wallet/com.example.zoldwallet.MainActivity
02-24 22:02:39.792  1407  1407 I Zygote  : Process 14019 exited due to signal (6)
02-24 22:02:40.085  1892 14052 I WindowManager: Screenshot max retries 4 of Token{a3931c6 ActivityRecord{1cf0ba1 u0 com.ammar.zold.wallet/com.example.zoldwallet.MainActivity t14858 f}} appWin=Window{88e9cb4 u0 Starting com.ammar.zold.wallet} drawState=4
02-24 22:02:40.093  1892 14052 W ActivityManager: Exception thrown during pause
02-24 22:02:40.093  1892 14052 W ActivityManager: android.os.DeadObjectException
02-24 22:02:40.093  1892 14052 W ActivityManager:   at android.os.BinderProxy.transactNative(Native Method)
02-24 22:02:40.093  1892 14052 W ActivityManager:   at android.os.BinderProxy.transact(Binder.java:503)
02-24 22:02:40.093  1892 14052 W ActivityManager:   at android.app.ApplicationThreadProxy.schedulePauseActivity(ApplicationThreadNative.java:727)
02-24 22:02:40.093  1892 14052 W ActivityManager:   at com.android.server.am.ActivityStack.startPausingLocked(ActivityStack.java:867)
02-24 22:02:40.093  1892 14052 W ActivityManager:   at com.android.server.am.ActivityStack.finishActivityLocked(ActivityStack.java:2907)
02-24 22:02:40.093  1892 14052 W ActivityManager:   at com.android.server.am.ActivityStack.finishTopRunningActivityLocked(ActivityStack.java:2763)
02-24 22:02:40.093  1892 14052 W ActivityManager:   at com.android.server.am.ActivityStackSupervisor.finishTopRunningActivityLocked(ActivityStackSupervisor.java:2760)
02-24 22:02:40.093  1892 14052 W ActivityManager:   at com.android.server.am.ActivityManagerService.handleAppCrashLocked(ActivityManagerService.java:12052)
02-24 22:02:40.093  1892 14052 W ActivityManager:   at com.android.server.am.ActivityManagerService.makeAppCrashingLocked(ActivityManagerService.java:11948)
02-24 22:02:40.093  1892 14052 W ActivityManager:   at com.android.server.am.ActivityManagerService.crashApplication(ActivityManagerService.java:12637)
02-24 22:02:40.093  1892 14052 W ActivityManager:   at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:12144)
02-24 22:02:40.093  1892 14052 W ActivityManager:   at com.android.server.am.NativeCrashListener$NativeCrashReporter.run(NativeCrashListener.java:86)
02-24 22:02:40.094   182   182 E lowmemorykiller: Error opening /proc/14019/oom_score_adj; errno=2
02-24 22:02:40.108  1892  2774 I ActivityManager: Process com.ammar.zold.wallet (pid 14019) has died
```
device: nexus-5 android-6.0.1

**Comment by ammaratef45** [comment]
@rultor deploy

**Comment by ammaratef45** [comment]
@rultor stop

**Comment by ammaratef45** [comment]
@rultor deploy

**Comment by ammaratef45** [comment]
@g4s8 is it okay now?

**Comment by g4s8** [comment]
@ammaratef45 yes, thanks
